 
let num1 = 10, num2 = 5, num3 = 3, num4 = 7, num5 = 2;

 // addition and substraction
console.log(num1 + num4); //17
console.log(num2 + num5); // 7
console.log(num4 - num1);// -3

 //multiplication and division
console.log(num1 * num4); //70
console.log(num5 * num4); //14
console.log(num2 / num5); //2.5

//exponential
 console.log (num3 ** num5); //9
 console.log (num2 ** num5);  //25

//modulus /remainder
console.log(num1 % num4); //3
console.log(num2 % num3); //2
console.log(num5 % num1); //2


//all together -order of operation

console.log( 3 ** 3 - 10 +25 % 2 + 7); //25

console.log(27 / 9 *3);  //9



